sampling: &sampling flex2mcmc
mcmc_args: &mcmc_args
  n_particles: 5 #25
  target_acceptance: 0.67
  forward_kl_weight: 1.0
  backward_kl_weight: 0.1
flow:
  name: RNVP
  params:
    num_flows: 5
    dim: null
  opt_params:
    lr: 0.001
  train_iters: 200
