gan_config:
  dp: true
  dataset: celeba
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: true
  generator:
    name: MMCSNGenerator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/sngan/G_CelebA_mimicry.pth
  discriminator:
    name: MMCSNDiscriminator
    params:
      mean: *mean
      std: *std
      output_layer: identity
    ckpt_path: checkpoints/sngan/D_CelebA_mimicry.pth
  thermalize:
    true: {}
    false:
      log_norm_const: -0.3887350251533396
      lipschitz_const: 11.739275976562501
      fake_score: -0.45755147576332095
      real_score: &real_score -0.018288894911529498
      mean_score: -0.23792018533742523
