gan_config:
  dp: true
  dataset: 
    name: cifar10
    params: {}
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: true
  generator:
    name: MMCDCGenerator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/dcgan_mimicry/DCGAN_G_CIFAR_100k.pth
  discriminator:
    name: MMCDCDiscriminator
    params:
      mean: *mean
      std: *std
      output_layer: identity
    ckpt_path: checkpoints/dcgan_mimicry/DCGAN_D_CIFAR_100k.pth

