train_transform:
  Normalize:
    mean: &mean [0.5, 0.5, 0.5]
    std: &std [0.5, 0.5, 0.5]

prior: normal

generator:
  name: DCGANGenerator
  params:
      ngpu: 1
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/dcgan/DCGAN_G_CIFAR_199.pth"

discriminator:
  name: DCGANDiscriminator
  params:
      ngpu: 1
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/dcgan/DCGAN_D_CIFAR_199.pth"
