gan_config:
  dp: true
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: uniform
  generator:
    name: SN_DCGAN_Generator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/wgan_gp_dot/DCGAN_G_CIFAR_WGAN-GP_150001.pth
  discriminator:
    name: WGANDiscriminator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/wgan_gp_dot/DCGAN_D_CIFAR_WGAN-GP_150001.pth
  thermalize:
    true: {}
    false:
      log_norm_const: 3.1634721852656957
      lipschitz_const: 10.185486975097659
      fake_score: &fake_score -1.736105637550354
      real_score: &real_score 2.3100808167457583
      mean_score: &mean_score 0.2869875895977021
