gan_config:
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: false
  label: &label true
  generator:
    name: StudioGen
    params:
      mean: *mean
      std: *std
      config: SNGAN.yaml
      label: *label
    ckpt_path: checkpoints/sngan/G_CIFAR_studio_current.pth
  discriminator:
    name: StudioDis
    params:
      mean: *mean
      std: *std
      output_layer: identity
      config: SNGAN.yaml
      label: *label
    ckpt_path: checkpoints/sngan/D_CIFAR_studio_current.pth
  thermalize:
    true:
      log_norm_const: -0.1995315524922824
      lipschitz_const: 12.774847021484375
    false:
      log_norm_const: 0.03418335853218875
      lipschitz_const: 12.961513012695312
