gan_config:
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  generator:
    name: SN_ResNet_Generator32
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/sngan/ResNet_G_CIFAR_SNGAN_Hinge_50000.pth
  discriminator:
    name: SN_DCGAN_Discriminator
    params:
      mean: *mean
      std: *std
    thermalize: true
    ckpt_path: checkpoints/sngan/DCGAN_D_CIFAR_SNGAN_NonSaturating_150001.pth
  thermalize:
    true:
      log_norm_const: -0.3751686000384026
      lipschitz_const: 12.00818842773438
    false:
      log_norm_const: 1.180305680238295
      lipschitz_const: 13.12786611328125
