gan_config:
  dp: true
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  generator:
    name: SN_ResNet_Generator32
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/sngan_resnet_hinge_dot/ResNet_G_CIFAR_SNGAN_Hinge_50000.pth
  discriminator:
    name: SN_DCGAN_Discriminator
    params:
      mean: *mean
      std: *std
    thermalize: true
    ckpt_path: checkpoints/sngan_resnet_hinge_dot/DCGAN_D_CIFAR_SNGAN_NonSaturating_150001.pth
  thermalize:
    true: {}
    false:
      log_norm_const: 0.6599634403382774
      lipschitz_const: 13.136835546874996
      fake_score: -0.35697615146636963
      real_score: &real_score 1.7757761883735657
      mean_score: &mean_score 0.709400018453598
