gan_config:
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: uniform
  generator:
    name: SN_DCGAN_Generator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/wgan_gp/DCGAN_G_CIFAR_WGAN-GP_150001.pth
  discriminator:
    name: WGANDiscriminator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/wgan_gp/DCGAN_D_CIFAR_WGAN-GP_150001.pth
  thermalize:
    true:
      log_norm_const: 1.347715135223855
      lipschitz_const: 1309.0426531249998
    false:
      log_norm_const: 1.9325980039693056
      lipschitz_const: 1308.7798875
      

