gan_config:
  dp: true
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: uniform
  generator:
    name: SN_DCGAN_Generator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/sngan_ns_dot/DCGAN_G_CIFAR_SNGAN_NonSaturating_150001.pth
  discriminator:
    name: SN_DCGAN_Discriminator
    params:
      mean: *mean
      std: *std
    thermalize: true
    ckpt_path: checkpoints/sngan_ns_dot/DCGAN_D_CIFAR_SNGAN_NonSaturating_150001.pth
  thermalize:
    true: {}
    false:
      log_norm_const: 0.08240829594605958
      lipschitz_const: 8.495529028320313
      fake_score: -0.5327480739355087
      real_score: &real_score 1.795639226436615
      mean_score: 0.6314455762505531
