gan_config:
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]

  prior: normal
  eval: true #true
  label: &label true

  generator:
    name: StudioGen
    params:
        mean: *mean
        std: *std
        config: SNGAN.yaml
        label: *label
    ckpt_path: "checkpoints/sngan/G_CIFAR_studio_current.pth"

  discriminator:
    name: StudioDis
    params:
        mean: *mean
        std: *std
        output_layer: 'identity'
        config: SNGAN.yaml
        label: *label
    ckpt_path: "checkpoints/sngan/D_CIFAR_studio_current.pth"

