gan_config:
  dp: true
  dataset: cifar10
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: false
  label: &label true
  generator:
    name: StudioGen
    params:
      mean: *mean
      std: *std
      config: SAGAN.yaml
      label: *label
    ckpt_path: checkpoints/sagan_studio/G_CIFAR_studio_best.pth
  discriminator:
    name: StudioDis
    params:
      mean: *mean
      std: *std
      output_layer: identity
      config: SAGAN.yaml
      label: *label
    ckpt_path: checkpoints/sagan_studio/D_CIFAR_studio_best.pth
  thermalize:
    true: {}
    false:
      log_norm_const: 0.23821046437544727
      lipschitz_const: 13.441802221679689
      fake_score: &fake_score -0.4312008327245712
      real_score: &real_score 1.5741937851905823
      mean_score: &mean_score 0.5714964762330055
