train_transform:
  Normalize:
    mean: &mean [0.5, 0.5, 0.5]
    std: &std [0.5, 0.5, 0.5]


generator:
  name: SN_ResNet_Generator32
  params:
      ngpu: 1
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/sngan/ResNet_G_CIFAR_SNGAN_Hinge_150001.pth"

discriminator:
  name: SN_DCGAN_Discriminator
  params:
      ngpu: 1
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/sngan/DCGAN_D_CIFAR_SNGAN_NonSaturating_150001.npz"
