gan_config:
  dp: true
  dataset: 
    name: cifar10
    params: {}
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: false
  label: &label true
  generator:
    name: StudioGen
    params:
      mean: *mean
      std: *std
      config: WGAN-GP.yaml
      label: *label
    ckpt_path: checkpoints/wgan_gp_studio/G_CIFAR_studio_best.pth
  discriminator:
    name: StudioDis
    params:
      mean: *mean
      std: *std
      output_layer: identity
      config: WGAN-GP.yaml
      label: *label
    ckpt_path: checkpoints/wgan_gp_studio/D_CIFAR_studio_best.pth
  thermalize:
    true: {}
    false:
      log_norm_const: -.inf
      lipschitz_const: 16.872395825195316
      fake_score: &fake_score -198.33542205810548
      real_score: &real_score -197.2879867553711
      mean_score: &mean_score -197.81170440673827
