gan_config:
  dp: true
  dataset: 
    name: cifar10
    params: {}
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: true
  generator:
    name: WGANGeneratorIN
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/wgan_gp_in/WGAN_GP_IN_G_CIFAR.pth
  discriminator:
    name: WGANDiscriminatorIN
    params:
      mean: *mean
      std: *std
      output_layer: identity
    ckpt_path: checkpoints/wgan_gp_in/WGAN_GP_IN_D_CIFAR.pth

