gan_config:
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: false
  generator:
    name: StudioGen
    params:
      mean: *mean
      std: *std
      config: DCGAN.yaml
    ckpt_path: checkpoints/dcgan/G_CIFAR_studio_best.pth
  discriminator:
    name: StudioDis
    params:
      mean: *mean
      std: *std
      output_layer: sigmoid
      config: DCGAN.yaml
    ckpt_path: checkpoints/dcgan/D_CIFAR_studio_best.pth
  thermalize:
    true:
      log_norm_const: -47.08530319183088
      lipschitz_const: 51.634661718749996
    false:
      log_norm_const: 1.5969345798136017
      lipschitz_const: 12.949544628906247
