gan_config:
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: false
  label: &label true
  generator:
    name: StudioGen
    params:
      mean: *mean
      std: *std
      config: SAGAN.yaml
      label: *label
    ckpt_path: checkpoints/sagan/G_CIFAR_studio_best.pth
  discriminator:
    name: StudioDis
    params:
      mean: *mean
      std: *std
      output_layer: identity
      config: SAGAN.yaml
      label: *label
    ckpt_path: checkpoints/sagan/D_CIFAR_studio_best.pth
  thermalize:
    true:
      log_norm_const: 0.10472944346574146
      lipschitz_const: 13.248738134765626
    false:
      log_norm_const: 0.2801069823604415
      lipschitz_const: 13.460238623046877

