train_transform:
  Normalize:
    mean: &mean [0.5, 0.5, 0.5]
    std: &std [0.5, 0.5, 0.5]


generator:
  name: SN_DCGAN_Generator
  params:
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/sngan/DCGAN_G_CIFAR_WGAN-GP_150001.pth"

discriminator:
  name: WGANDiscriminator
  params:
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/wgan_gp/DCGAN_G_CIFAR_WGAN-GP_150001.pth"
