train_transform:
  Normalize:
    mean: &mean [0.5, 0.5, 0.5]
    std: &std [0.5, 0.5, 0.5]


generator:
  name: DCGANGenerator
  params:
      ngpu: 1
      mean: *mean
      std: *std
  ckpt_path: "checkpoints/dcgan/netG_epoch_199.pth"

discriminator:
  name: DCGANDiscriminator
  params:
      ngpu: 1
  ckpt_path: "checkpoints/dcgan/netD_epoch_199.pth"
