generator:
  name: DCGANGenerator
  params:
      ngpu: 1
  ckpt_path: "checkpoints/dcgan/netG_epoch_199.pth"

discriminator:
  name: DCGANDiscriminator
  params:
      ngpu: 1
  ckpt_path: "checkpoints/dcgan/netD_epoch_199.pth"

