gan_config:
  dp: false
  dataset: gaussians_grid
  train_transform:
    Normalize:
      mean: &mean [0., 0.]
      std: &std [1.415, 1.415]
  prior: normal
  eval: true
  generator:
    name: MLPGenerator
    params:
      mean: *mean
      std: *std
      z_dim: 2
      n_layers: 3
      n_hid: 128
      n_out: 2
    ckpt_path: checkpoints/mlp/G_25_gauss_wass.pth
  discriminator:
    name: MLPDiscriminator
    params:
      mean: *mean
      std: *std
      n_layers: 3
      n_hid: 256
      n_in: 2
    ckpt_path: checkpoints/mlp/D_25_gauss_wass.pth
  fake_score: 1.120748509168625
  real_score: &real_score 1.3069784998893739
  mean_score: 1.2138635045289994
