gan_config:
  dp: false
  dataset: gaussians_ring
  train_transform:
    Normalize:
      mean: &mean [0., 0.]
      std: &std [1., 1.]
  prior: normal
  eval: true
  generator:
    name: MLPGenerator
    params:
      mean: *mean
      std: *std
      z_dim: 256
      n_layers: 2
      n_hid: 128
      n_out: 2
    ckpt_path: checkpoints/mlp/G_8_gauss.pth
  discriminator:
    name: MLPDiscriminator
    params:
      mean: *mean
      std: *std
      n_layers: 2
      n_hid: 128
      n_in: 2
    ckpt_path: checkpoints/mlp/D_8_gauss.pth
  fake_score: -1.7566776394844055
  real_score: &real_score 8.224320197105408
  mean_score: 3.233821278810501


n_epochs: &n_epochs 400
n_dis: &n_dis 3 #10
criterion_g: &criterion_g
  name: JensenLoss
criterion_d: &criterion_d
  name: JensenLoss
optimizer_g: &optimizer_g
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.999]
optimizer_d: &optimizer_d
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.999]

