feature: &feature
  name: ClusterFeature
  params: 
    device: *device
    clusters_path: data/cifar10/kmeans_resnet34.npz
    ref_stats_path: stats/ClusterFeature_resnet34_cifar10.npz
    embedding_model: resnet34
    version: *version
    kernel: *kernel
    dis_emb: False
    opt_params:
      name:
        SGD
      params:  
        # momentum: 0.1
        # nesterov: True
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1

