feature: &feature
  name: ClusterFeature
  params: 
    device: *device
    dis: null
    clusters_path: data/cifar10/kmeans.npz
    ref_stats_path: stats/ClusterFeature_v1_cifar10.npz
    version: 1 #0
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
