feature: &feature
  name: CMDFeature
  params: 
    device: *device
    ref_stats_path: stats/CMDFeature_cifar10.npz
    dp: true
    n_moments: 3
    dataloader: true
    kernel: *kernel
    dis_emb: *dis_emb
    gan: *dis_emb
    opt_params:
      name:
        SGD
      params:  
        # momentum: 0.1
        # nesterov: True
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
