feature: &feature
  name: CMDFeature
  params: 
    device: *device
    dataloader: null
    ref_stats_path: stats/CMDFeature_2d.npz
    embedding_model: null
    dp: true
    n_moments: 3
    dis_emb: *dis_emb
    gan: null
    batch_size: *batch_size
    opt_params:
      name:
        SGD
      params:  
        # momentum: 0.1
        # nesterov: True
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
