feature: &feature
  name: DiscriminatorGradientFeature
  params: 
    device: *device
    dis: null
    ref_stats_path: stats/DiscriminatorGradientFeature_cifar10.npz
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
