feature: &feature
  name: DiscriminatorFeature
  params: 
    device: *device
    dis: null
    ref_score: *real_score #*mean_score
    ref_stats_path: stats/DiscriminatorFeature.npz
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.0 #1 #0.025 #0.075 #1
