feature: &feature
  name: DiscriminatorFeature
  params: 
    device: *device
    dis: null
    ref_score: *real_score #*mean_score
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.9
        nesterov: True
