feature: &feature
  name: EfficientNetFeature
  params: 
    device: *device
    ref_stats_path: stats/EfficientNetFeature34.npz
    dp: true
    opt_params:
      name:
        SGD
      params:  
        # momentum: 0.1
        # nesterov: True
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
