feature: &feature
  name: KernelPCAFeature
  params: 
    device: *device
    info_path: data/cifar10/pca_rbf.npz
    ref_stats_path: stats/KernelPCAFeature_cifar10.npz
    batch_size: *batch_size
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
