feature: &feature
  name: PCAFeature
  params: 
    device: *device
    info_path: data/cifar10/pca.npz
    ref_stats_path: stats/PCAFeature_cifar10.npz
    opt_params:
      name:
        SGD
      params:  
        momentum: 0.0 #0.1
        nesterov: False #True
        weight_decay: 0.01 #0.025 #0.075 #1
