dir: &dir log/sum_feature
sub_dir: &sub_dir test
n_steps: &n_steps 1000
every: &every 10
seed: null

device: &device cuda

sample: &sample_params
  save_dir: *dir
  sub_dir: *sub_dir
  
  feature:
    name: SumFeature
    params:
      features:
        - feature1:
          name: ResnetFeature
          params:
            device: *device
            data_stat_path: stats/resnet34_stats_cifar10.npz
            dp: true
        - feature2:
          name: DiscriminatorFeature
          params:
            device: *device
            dis: true
      dis: true

  total_n: 100
  batch_size: 100
  save_every: *every

  params:
    n_steps: *n_steps
    save_every: *every
    burn_in_steps: 10

    n_sampling_steps: &n_sampling_steps 1 #10
    weight_step: 0.1 #0.1 #0.01
    step_size: 0.001 #0.01
    save_every: *n_sampling_steps

compute_fid:


compute_is:


wandb_init_params: &wandb_init_params
  project: &wandb_project soul_gan
  entity: &wandb_account sverdoot
  name: &name resnet34_discriminator_feature
  config: *sample_params

callbacks:
  feature_callbacks:
    inception_score:
      name: InceptionScoreCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
        dp: true
    fid:
      name: FIDCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
        data_stat_path: stats/fid_stats_cifar10.npz

    wandb:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - "inception score"
          - weight_ResnetFeature
          - weight_DiscriminatorFeature
          - fid
          - D(G(z))
    wandb_imgs:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - imgs

logging:
  wandb: null

