dir: &dir log/cluster_resnet34_feature
n_steps: &n_steps 1000
every: &every 25
seed: null

device: &device 'cuda'
total_n: &total_n 10000 #10000 #
batch_size: &batch_size 1000


data_batch_size: *batch_size
weight_step: &weight_step 3 #0.5 #0.01
step_size: &step_size 0.001
name: &name dcgan_cluster_resnet34
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0. #10
sub_dir: &sub_dir dcgan
suffix: *step_size
version: &version '0'
kernel: &kernel GaussianKernel
