dir: &dir log/identity_feature
n_steps: &n_steps 1000
every: &every 25
seed: null

device: &device 'cuda'
total_n: &total_n 1000 #
batch_size: &batch_size 1000
data_batch_size: *batch_size
weight_step: &weight_step 0.1 # 0.1
step_size: &step_size 0.0001   # 0.0001 goood
name: &name dcgan_identity
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0. #10
sub_dir: &sub_dir dcgan
suffix: *step_size
