dir: &dir log
n_steps: &n_steps 5000
every: &every 10
seed: null
device: &device 'cuda'

sample: &sample_params
  save_dir: *dir
  sub_dir: test
  
  feature:
    name: DiscriminatorFeature
    params: 
      device: *device
      dis: null

  total_n: 1000
  batch_size: 100
  save_every: *every

  params:
    n_steps: *n_steps
    save_every: *every
    burn_in_steps: 0

    n_sampling_steps: &n_sampling_steps 1
    weight_step: 0.01 #0.1
    step_size: 0.001 #0.01
    save_every: *n_sampling_steps


compute_fid:


compute_is:



wandb_init_params: &wandb_init_params
  project: &wandb_project soul_gan
  entity: &wandb_account sverdoot
  name: &name discriminator_feature
  config: *sample_params

callbacks:
  feature_callbacks:
    inception_score:
      name: InceptionScoreCallback
      params:
        invoke_every: *n_sampling_steps
        device: *device
        update_input: true

    wandb:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: *n_sampling_steps
        keys:
          - "inception score"
          - weight
          - D(G(z))
    wandb_imgs:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - imgs

logging:
  wandb: null

