dir: &dir log/dumb_feature
sub_dir: &sub_dir test3
n_steps: &n_steps 1000
every: &every 10
seed: null
device: &device 'cuda'


sample: &sample_params
  save_dir: *dir
  sub_dir: *sub_dir
  
  feature:
    name: DumbFeature
    params: 
      device: *device
      dis: null

  total_n: 100 #5000
  batch_size: 100 #250
  save_every: *every

  params:
    n_steps: *n_steps
    save_every: *every
    burn_in_steps: 0

    n_sampling_steps: &n_sampling_steps 1
    weight_step: 0.0
    step_size: 0.01


compute_fid:
  results_dir: *dir
  sub_dir: *sub_dir

compute_is: {}


params: &params
    sample_params: *sample_params
    name: &name dumb
    feature:
      name: dumb

wandb_init_params: &wandb_init_params
  project: &wandb_project soul_gan
  entity: &wandb_account sverdoot
  name: *name
  config: *params


callbacks:
  feature_callbacks:
    discriminator:
      name: DiscriminatorCallback
      params:
        dis: null
        invoke_every: 50
        device: *device
        update_input: true
    inception_score:
      name: InceptionScoreCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
    fid:
      name: FIDCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
        data_stat_path: stats/fid_stats_cifar10.npz

    wandb:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: True
        invoke_every: 50
        keys:
          - "inception score"
          - fid
          - D(G(z))
    wandb_imgs:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - imgs

logging:
  wandb: null

