dir: &dir log/inception_feature
n_steps: &n_steps 2000
every: &every 10
seed: null
device: &device cuda


sample: &sample_params
  save_dir: *dir
  sub_dir: test
  
  feature:
    name: inception_score
    params: 
      device: *device
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  total_n: 100
  batch_size: 100
  save_every: *every

  params:
    n_steps: *n_steps
    save_every: *every
    burn_in_steps: 10

    n_sampling_steps: &n_sampling_steps 1 #10
    weight_step: 0.01 #0.1 #0.01
    step_size: 0.005 #0.01
    save_every: *n_sampling_steps

compute_fid:


compute_is:


wandb_init_params: &wandb_init_params
  project: &wandb_project soul_gan
  entity: &wandb_account sverdoot
  name: &name inception_score
  config: *sample_params

callbacks:
  feature_callbacks:
    inception_score:
      name: InceptionScoreCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
    fid:
      name: FIDCallback
      params:
        invoke_every: 50
        device: *device
        update_input: true
        data_stat_path: stats/fid_stats_cifar10.npz

    wandb:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - "inception score"
          - weight
          - fid
    wandb_imgs:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 50
        keys:
          - imgs

logging:
  wandb: null

