dir: &dir log/cluster_feature
n_steps: &n_steps 1000 #0
every: &every 25
seed: null
device: &device 'cuda'
total_n: &total_n 10000 #
batch_size: &batch_size 10000
weight_step: &weight_step 1 #0.01
step_size: &step_size 0.1
name: &name mlp_cluster
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir mlp
suffix: *step_size
