dir: &dir log/dumb_feature
n_steps: &n_steps 500 #300
every: &every 25
seed: null

device: &device 'cuda'
total_n: &total_n 5000
batch_size: &batch_size  600
data_batch_size: *batch_size
weight_step: &weight_step 0.01
step_size: &step_size 0.01
name: &name mmc_sngan_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir mmc_sngan
suffix: *step_size
