dir: &dir log/dumb_feature
n_steps: &n_steps 1000 #500 #300
every: &every 50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
total_n: &total_n 1000 #0
batch_size: &batch_size 100  #400 #300
data_batch_size: *batch_size
weight_step: &weight_step 0.1
step_size: &step_size 0.001
name: &name mmc_sngan_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir mmc_sngan
suffix: *step_size
