dir: &dir log/dumb_feature
n_steps: &n_steps 1000
every: &every 50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
total_n: &total_n 10000
batch_size: &batch_size 1000
data_batch_size: *batch_size
weight_step: &weight_step 0.1 #0.01
step_size: &step_size 0.01
name: &name stacked_mnist_dcgan_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir stacked_mnist_dcgan
suffix: *step_size
# version: &version '0'
kernel: &kernel GaussianKernel
