dir: &dir log/dumb_feature
n_steps: &n_steps 100
every: &every 25
seed: null
device: &device 'cuda'
total_n: &total_n 1000 #0
batch_size: &batch_size 80 #100 #250
weight_step: &weight_step 0.01
step_size: &step_size 0.01
name: &name studio_stylegan2_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir studio_stylegan2
suffix: *step_size
