dir: &dir log/resnet34_feature
n_steps: &n_steps 500 #200
every: &every 20 #50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
total_n: &total_n 64 #10000 #0
batch_size: &batch_size 64
data_batch_size: *batch_size
weight_step: &weight_step 0.1
step_size: &step_size 0.003
name: &name studio_stylegan2_resnet34
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir studio_stylegan2
suffix: *step_size
