dir: &dir log/dumb_feature
n_steps: &n_steps 500
every: &every 25
seed: null

device: &device 'cuda'
total_n: &total_n 10000 #0
batch_size: &batch_size 120 #100 #250
data_batch_size: *batch_size
weight_step: &weight_step 0.001
step_size: &step_size 0.01
name: &name studio_stylegan2_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0.
sub_dir: &sub_dir studio_stylegan2
suffix: *step_size
